[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput --clear"]

[start]
cmd = "python manage.py migrate --noinput && python crear_superusuario.py && python agregar_datos_basicos.py && python agregar_banners.py && gunicorn mi_portafolio.wsgi:application --bind 0.0.0.0:$PORT --log-file -"
