# Generated by Django 5.1.6 on 2025-09-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('utm_source', models.CharField(max_length=100)),
                ('utm_medium', models.CharField(max_length=100)),
                ('utm_campaign', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('titulo_profesional', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Perfil',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proyectos/')),
                ('url', models.URLField(blank=True)),
                ('tecnologias', models.CharField(help_text='Separadas por comas', max_length=200)),
                ('fecha', models.DateField()),
                ('destacado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.IntegerField(default=50, help_text='Nivel de 0 a 100')),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['-fecha_envio'], 'verbose_name_plural': 'Contactos'},
        ),
        migrations.AddField(
            model_name='contacto',
            name='asunto',
            field=models.CharField(default='Consulta general', max_length=200, verbose_name='Asunto'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre completo'),
        ),
    ]
