# Generated by Django 4.2.24 on 2025-09-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_banner_perfil_proyecto_skill_alter_contacto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.URLField(blank=True, help_text='URL de la imagen de perfil', null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.URLField(blank=True, help_text='URL de la imagen del proyecto', null=True),
        ),
    ]
