# Generated by Django 5.2.6 on 2025-09-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('palabras_clave', models.CharField(blank=True, max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recetas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
