# Generated by Django 4.2.24 on 2025-09-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='imagen',
            field=models.URLField(blank=True, help_text='URL de la imagen de la receta', null=True),
        ),
    ]
